(define (problem soko-ni-pallette)
  (:domain sokorobotto)
  (:objects
    shipment1 - shipment
    order1 - order
    loc1 loc2 loc3 loc4 loc5 pack1 - location
    robot1 robot2 - robot
    pallette1 pallette2 pallette3 pallette4 - pallette
    tv1 chair1 socks1 socks2 hat1 book1 computer1 computer2 - saleitem
    )
  (:init
    (ships shipment1 order1)
    (orders order1 socks1)
    (orders order1 book1)
    (unstarted shipment1)
    (contains pallette1 tv1)
    (contains pallette1 chair1)
    (contains pallette2 socks1)
    (contains pallette2 socks2)
    (contains pallette3 hat1)
    (contains pallette3 book1)
    (contains pallette4 computer1)
    (contains pallette4 computer2)
    (packing-location pack1)
    (available pack1)
    (free robot1)
    (free robot2)
    (connected loc1 loc2)
    (connected loc2 loc1)
    (connected loc2 pack1)
    (connected pack1 loc2)
    (connected loc1 loc3)
    (connected loc3 loc1)
    (connected loc3 loc4)
    (connected loc4 loc3)
    (connected loc2 loc4)
    (connected loc4 loc2)
    (connected loc4 loc5)
    (connected loc5 loc4)
    (connected loc5 pack1)
    (connected pack1 loc5)
    (at pallette1 loc1)
    (at pallette2 loc3)
    (at pallette3 loc4)
    (at pallette4 loc5)
    (at robot1 loc2)
    (at robot2 pack1)
    (no-robot loc1)
    (no-robot loc3)
    (no-robot loc4)
    (no-robot loc5)
    (no-pallette pack1)
    (no-pallette loc2)
    (available pack1)
    )
  (:goal (and (includes shipment1 socks1)
              (includes shipment1 book1)))
)